### ISSUE TITLE
你好。你的shopee api的项目对我很有启发。能否交流下技术细节呢

### ISSUE THREAD

**Issue by no13bus** [passwind/go-shopee-v2#1]
你好。
我是一名程序员，在北京。最近也在开始对接 shopee 的开放平台。搜到了你的项目。你的shopee api的项目对我很有启发。能否交流下api接口申请，资质审核，以及其他的技术细节呢。  我的微信  no13bus.  邮箱 no13bus@gmail.com

**Comment by passwind** [comment]
到open.shopee.com上申请开通开发者账号，剩下的事就只能听天由命了：0

**Comment by no13bus** [comment]
@passwind 你之前申请了多久接口权限才下来的？中间他有什么确认过什么东西吗

**Comment by passwind** [comment]
我自己申请的还没成功通过审核，现在用的是别人之前申请的：（
